version: "3"

services:
  nginx:
    image: nginx:1.25
    container_name: youtube_api_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - load_balancer
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: youtube_api_postgres
    environment:
      POSTGRES_PASSWORD: lLhi3zdgLRQjLfz
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - db
    restart: unless-stopped

  adminer:
    image: adminer:4.8.1
    container_name: youtube_api_adminer
    ports:
      - "5000:8080"
    networks:
      - db
    depends_on:
      - database
    restart: unless-stopped

  db_updater:
    image: yt_db_updater
    build: ./db_updater
    env_file:
      - ".env"
    networks:
      - db
    depends_on:
      - database
      - cache
    restart: unless-stopped

  api:
    image: yt_api
    build: ./api
    deploy:
      replicas: 1
    env_file:
      - ".env"
    networks:
      - load_balancer
      - db
    depends_on:
      - database
    restart: unless-stopped

  dashboard:
    image: yt_dashboard
    build: ./dashboard
    env_file:
      - ".env"
    networks:
      - db
    depends_on:
      - database
    ports:
      - "8501:8501"
    restart: unless-stopped

  cache:
    image: redis:7.2.4
    container_name: youtube_api_redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - db
    depends_on:
      - database
    restart: unless-stopped

networks:
  load_balancer:
    name: youtube_api_load_balancer
  db:
    name: youtube_api_database

volumes:
  postgres_data:
    name: youtube_api_postgres_data
  redis_data:
    name: youtube_api_redis_data
