version: '3'

services:
    nginx:
      image: nginx
      container_name: youtube_api_nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      depends_on:
        - api
      networks:
        - load_balancer

    database:
      image: postgres:16
      container_name: youtube_api_postgres
      environment:
        POSTGRES_PASSWORD: lLhi3zdgLRQjLfz
        PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/pgdata
      networks:
        - db

    adminer:
      image: adminer
      container_name: youtube_api_adminer
      ports:
        - "5000:8080"
      networks:
        - db
      depends_on:
        - database

    api:
      image: yt_api
      build: ./api
      deploy:
        replicas: 2
      environment:
        POSTGRES_URL: postgresql://postgres:lLhi3zdgLRQjLfz@database:5432/youtube
      networks:
        - load_balancer
        - db
      depends_on:
        - database

networks:
  load_balancer:
    name: youtube_api_load_balancer
  db:
    name: youtube_api_database

volumes:
  postgres_data:
    name: youtube_api_postgres_data